---
# tasks file for ubuntu-install-ssl-localhost
- name: Install python-pip
  apt:
    name: ['python-pip']
    state: present

- name: Python OpenSSL dependencies install
  pip:
    name: pyOpenSSL
    state: present

- name: Dir exists for local self-signed ssl
  file:
    path: /etc/ssl/localhost
    state: directory

- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: /etc/ssl/localhost/localhost.key

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: /etc/ssl/localhost/localhost.csr
    privatekey_path: /etc/ssl/localhost/localhost.key
    common_name: "localhost"

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/ssl/localhost/localhost.cert
    privatekey_path: /etc/ssl/localhost/localhost.key
    csr_path: /etc/ssl/localhost/localhost.csr
    provider: selfsigned
    valid_in: 90000000000
