---
# tasks file for ubuntu-install-bind9
- name: Install bind9
  apt:
    name: ['bind9']
    state: present

- name: Template named.conf.options
  template: src=named.conf.options dest=/etc/bind/named.conf.options
  notify:
  - Restart bind9

- name: Create rfc2136 key
  shell: /usr/sbin/tsig-keygen -a HMAC-SHA512 admin >> /etc/bind/named.conf.options
  notify:
  - Restart bind9

- name: Auto start bind9
  service:
    name: bind9
    enabled: yes

