---
# tasks file for ubuntu-install-mysql
- name: Install mysql-server
  apt:
    name: ['mysql-server']
    state: present
  notify:
  - Stop mysql
  - Mov mysql data to home
  - Create link to mysql data
  - Template config

- name: Auto start mysql
  service:
    name: mysql
    enabled: yes

- name: Disable apparmor for mysql
  file:
    src: /etc/apparmor.d/usr.sbin.mysqld
    dest: /etc/apparmor.d/disable/usr.sbin.mysqld
    owner: root
    group: root
    state: link

- name: Reboot host
  reboot:
    reboot_timeout: 600

